accounts/urls.py
from django.conf.urls import patterns, url
from views import Logout

urlpatterns = patterns('',
    url(r'^$', Logout.as_view(), name='logout'),
)

tweets/urls.py
from django.conf.urls import patterns, url
from views import Index

urlpatterns = patterns('',
    url(r'^$', Index.as_view(), name='index'),
)

twitterapp/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

# Views
from views import Index

urlpatterns = patterns('',
    # Admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # Third Party Url
    url(r'', include('social_auth.urls')),

    # Pages Views
    url(r'^$', Index.as_view(), name='index'),

    # App url redirects
    url(r'^account/$', include('accounts.urls', namespace='accounts')),
    url(r'^tweet/$', include('tweets.urls', namespace='tweets'))

)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
    )

accounts/models.py
""" All models needed for account registration """
from django.db import models
from django.contrib.auth.models import AbstractUser

class CustomUser(AbstractUser):
    """ Model -- Stores information on users

    This model extends default Django User and adds photo field
    """
    photo = models.ImageField(upload_to='profiles/', null=True)

tweets/models.py
from django.db import models
from django.conf import settings
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel


class DefaultManager(models.Manager):
    """
    Provides a 'default' method to grab the default instance
    for a given model
    """

    def default(self):
        """ 
        returns object instance with a name of 'Unknown'
        """
        return self.get(name='Unknown')


class Category(TimeStampedModel):
    """
    Categories of products
    """
    name = models.CharField(_(u'Category Name'), max_length=255)

    objects = DefaultManager()

    def __unicode__(self):
        return self.name


class Product(TimeStampedModel):
    """ 
    Product information
    """
    name = models.CharField(_(u'Product Name'), max_length=255)
    category = models.ForeignKey(Category)

    objects = DefaultManager()

    def __unicode__(self):
        return self.name


def get_default_product():
    """
    Returns the default 'Unknown' product
    """
    return Product.objects.get_or_create(name='Unknown', category=get_default_category())


def get_default_category():
    """
    Returns the default 'Unknown' category
    """
    return Category.objects.get_or_create(name='Unknown')[0]


def validate_length(string):
    """
    Validates that string is less than 110 chars

    Acts as validator for Tweets
    """
    if len(string) > 110:
        raise ValidationError('Tweet must be less than 110 characters')


class Tweet(TimeStampedModel):
    """ 
    Tweet Information
    """
    message = models.TextField(_(u'Message to tweet'), max_length=110, blank=False, validators=[validate_length])
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True)
    category = models.ForeignKey(Category, default=get_default_category)
    product = models.ForeignKey(Product, default=get_default_product)
    published_on = models.DateTimeField(null=True)

tweets/forms.py
from django import forms

from .models import Tweet


class TweetsForm(forms.ModelForm):

    class Meta:
        model = Tweet
        fields = ('message',)

    def __init__(self, user, *args, **kwargs):
        """Store user for later use and add error message"""
        super(TweetsForm, self).__init__(*args, **kwargs)
        self.user = user

        # add custom error messages
        self.fields['message'].error_messages = {'required': 'We need a message in order to tweet!'}

    def save(self, commit=True):
        """
        TODO: Add user to created_by field, parse tweet to find category/product and post twitter status

        But remember, only posts to twitter if a category is found in the tweet
        """


        raise NotImplementedError("Need to implement save method on TweetsForm")

accounts/views.py
"""All views dealing with accounts/authentication/authorization """

from django.views.generic import View
from django.shortcuts import HttpResponseRedirect
from django.contrib.auth import logout
from django.core.urlresolvers import reverse


class Logout(View):

    def dispatch(self, request, *args, **kwargs):
        logout(request)
        return HttpResponseRedirect(reverse('index'))

tweets/views.py
import twitter
from django.conf import settings
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import View
from braces.views import LoginRequiredMixin

from forms import TweetsForm
from models import get_default_category

class Index(LoginRequiredMixin, View):
    """ View -- Handles all tweet submissions """
    form_class = TweetsForm

    def post(self, request, *args, **kwargs):
        """ Verify tweet submission is valid, handles errors and posts to Twitter if appropriate"""
        form = self.form_class(data=request.POST, user=request.user)

        if form.is_valid():
            instance = form.save()

            # Deal with posting twitter status
            posted_status = False
            if instance.category != get_default_category():
                # Create tweeted message and post status
                tweeted_message = "RT:<%s>%s#Custom#%s" % (instance.created_by.username, instance.message, instance.category)
                api = twitter.Api(consumer_key=settings.TWITTER_CONSUMER_KEY, consumer_secret=settings.TWITTER_CONSUMER_SECRET,
                                  access_token_key=settings.TWITTER_USER_OAUTH_TOKEN, access_token_secret=settings.TWITTER_USER_OAUTH_TOKEN_SECRET)
                api.PostUpdate(status=tweeted_message)

                # Save time published and update postedStatus
                instance.published_on = timezone.now()
                instance.save()
                posteds_status = True

            return render(request, 'tweets/index.html', {'form': self.form_class(user=request.user), 'success': True, 'posted_status': posted_status})
        return render(request, 'tweets/index.html', {'form': form})

    def get(self, request, *args, **kwargs):
        """ Display the Tweet form """
        return render(request, 'tweets/index.html', {'form': self.form_class(user=request.user)})

twitterapp/views.py
"""Main page views -- basically static pages"""
from django.views.generic import View
from django.shortcuts import render

class Index(View):
    """Displays welcome page"""
    def get(self, request, *args, **kwargs):
        return render(request, 'pages/index.html')

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link type="text/css" rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}" />
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
    </head>
    <body>

        <!--- Navigation -->
        <div class="container-fluid">
            <div class="navbar navbar-inverse navbar-static-top top-navbar-container">
                <ul class="nav navbar-nav pull-right top-nav">

                    {% if not user.is_authenticated %}
                        <li><a href="{% url 'socialauth_begin' 'twitter' %}">Login</a></li>
                    {% else %}
                        <li><a href="{% url 'index' %}">CM Engineering Test</a></li>
                        <li><a href="{% url 'tweets:index' %}">Tweet Now!</a> </li>
                        <li class="dropdown">
                            <a href="#" role="button" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}</a>
                            <ul class="dropdown-menu" role="menu">
                                <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                            </ul>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
        {% block content %}{% endblock %}
    </body>
    <footer>
        <!--- Load Javascript -->
        <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
        {% block extraJavaScript %}{% endblock %}
    </footer>
</html>

templates/pages/index.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block content %}
    <div class="container-fluid main-banner">
        <div class="row-fluid">
            <div class="hero-unit">
                <div class="row-fluid">
                    <div class="col-lg-12 text-center">
                        <div class="row-fluid">
                            <h1 id="title-app-lead">CustomMade Engineering Test</h1>
                        </div>
                        <div class="row-fluid secondary-comment">
                            <h2> </h2>
                        </div>
                        <div class="row-fluid text-center">
                            <a class="btn btn-primary btn-danger btn-large col-lg-4 col-offset-4"
                                {% if user.is_authenticated %} href="{% url 'tweets:index' %}">Send a Tweet
                                {% else %} href="{% url 'socialauth_begin' 'twitter' %}">Login with Twitter
                                {% endif %}
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

templates/tweets/index.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block title %}Tweets!{% endblock %}
{% block content %}
    {% if form.errors.message %}
        <!-- Deal with form errors -->
        <div id="form-errors" class="alert-danger navbar-fixed-top">
            <button type="button" class="close fade in" data-dismiss="alert">&times;</button>
            <div class="error text-center">{{ form.errors.message }}</div>
        </div>
    {% endif %}

    {% if success %}
        <div id="form-errors" class="alert-success navbar-fixed-top">
            <button type="button" class="close fade in" data-dismiss="alert">&times;</button>
            <p class="success text-center">Success! You just submitted a tweet</p>
        </div>
    {% endif %}

    <div class="row-fluid main-banner">
        <div class="col-lg-4 col-offset-1">
            <h2 id="page-lead">
                Please send out a tweet!
            </h2>

            <h3 id="secondary">
                If you include a category, <strike>we will post it to twitter!</strike> (you need to include this functionality).
            </h3>
        </div>
        <div class="col-lg-7">
            <form id="tweet-form" class="form-horizontal" action="#" method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <div class="col-lg-10 col-offset-1">
                        {{ form.message | attr:"class:form-control" | attr:"row:3" | attr:"placeholder:Type out a tweet! It must be less than 110 characters though"}}
                        <button type="submit" class="btn-large btn btn-danger btn-primary">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}